apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pg-backup.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pg-backup.labels" . | nindent 4 }}
data:
  backup.sh: |
{{ .Files.Get "scripts/backup.sh" | indent 4 }}
  restore.sh: |
{{ .Files.Get "scripts/restore.sh" | indent 4 }}
