apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stock-analyzer.fullname" . }}-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stock-analyzer.labels" . | nindent 4 }}
data:
  analyzer.py: |
{{ .Files.Get "scripts/analyzer.py" | indent 4 }}
