apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.config.internalPort }}
      targetPort: {{ .Values.config.internalPort }}
      name: internal
    - port: {{ .Values.config.externalPort }}
      targetPort: {{ .Values.config.externalPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: external
