apiVersion: v1
kind: Service
metadata:
  name: {{ include "akhq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akhq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "akhq.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: http
