apiVersion: v2
name: kube-prometheus-stack
description: Prometheus Operator with Grafana, Prometheus, and Alertmanager
type: application
version: 1.0.0
appVersion: "v0.70.0"
dependencies:
  - name: kube-prometheus-stack
    version: "56.6.2"
    repository: https://prometheus-community.github.io/helm-charts
