apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.apiNodePort }}
      {{- end }}
      name: api
    - port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consolePort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.consoleNodePort }}
      {{- end }}
      name: console
