apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flink.fullname" . }}-taskmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flink.labels" . | nindent 4 }}
    component: taskmanager
spec:
  replicas: {{ .Values.taskmanager.replicas }}
  selector:
    matchLabels:
      {{- include "flink.taskmanagerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flink.taskmanagerSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: taskmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["taskmanager"]
          ports:
            - containerPort: {{ .Values.taskmanager.rpcPort }}
              name: rpc
          volumeMounts:
            - name: flink-config
              mountPath: /opt/flink/conf/flink-conf.yaml
              subPath: flink-conf.yaml
          resources:
            requests:
              memory: {{ .Values.taskmanager.resources.requests.memory | quote }}
              cpu: {{ .Values.taskmanager.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.taskmanager.resources.limits.memory | quote }}
              cpu: {{ .Values.taskmanager.resources.limits.cpu | quote }}
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          readinessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 15
            periodSeconds: 5
          {{- end }}
      volumes:
        - name: flink-config
          configMap:
            name: {{ include "flink.fullname" . }}-config
