apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    component: master
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "spark.masterSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.master.sparkPort }}
      targetPort: {{ .Values.master.sparkPort }}
      name: spark
    - port: {{ .Values.master.webUiPort }}
      targetPort: {{ .Values.master.webUiPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.webUiNodePort }}
      {{- end }}
      name: web-ui
